using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace tht3 {

    /// <summary>
    /// A class that perform Guessing Game in which
    /// user picks up an integer value from the range [1 - 10] and a
    /// value is then in the same range is randomly generated by the computer.
    /// Both the values (User and Computer) are then compared and accordingly 
    /// right and wrong guesses are recorded.
    /// 
    /// Name: Harmanjeet Singh 
    /// StudentID: N9920811
    /// Date: 1st September, 2017
    /// </summary>
    public partial class Form1 : Form {

        //Global variables 
        int correctGuesses = 0;
        int incorrectGuesses = 0;

        //Constants
        const int NOT_ACCEPTED_VALUE = 0;
        const int MIN_VAL = 1;
        const int MAX_VAL = 11;
        const int INCREMENT_EACH_GUESS = 1;
        static Random RANDOM_CHOICE = new Random();

        public Form1() {
            InitializeComponent();
        }

        private void numericUpDownUserValue_ValueChanged(object sender, EventArgs e) {

            EnableOrDisableCheckButton();

        }

        private void buttonCheck_Click(object sender, EventArgs e) {

            PlayGame(GetComputerValue());

        }

        private void radioButtonYes_CheckedChanged(object sender, EventArgs e) {

            ResetOnYesClick();

        }

        private void radioButtonNo_CheckedChanged(object sender, EventArgs e) {
            ResetOnNoClick();

        }

        /// <summary>
        /// Enables or disables Check Button 
        /// depending on the value selected by the user
        /// </summary>
        public void EnableOrDisableCheckButton() {

            decimal usersValue = numericUpDownUserValue.Value;

            if (usersValue == NOT_ACCEPTED_VALUE) {
                buttonCheck.Enabled = false;

            } else {
                buttonCheck.Enabled = true;

            }
        }

        /// <summary>
        /// Play the Game by getting values from user and computer
        /// and then comparing them and then record the correct and
        /// incorrect guesses.
        /// </summary>
        /// <param name="computersValue">Random value generated by computer</param>
        public void PlayGame(int computersValue) {

            decimal usersValue = numericUpDownUserValue.Value;

            numericUpDownUserValue.Enabled = false;
            buttonCheck.Enabled = false;

            if (computersValue == usersValue) {

                labelResultMessage.Visible = true;
                labelResultMessage.ForeColor = Color.Green;
                labelResultMessage.Text = "You guessed the number!    ";
                correctGuesses += INCREMENT_EACH_GUESS;
                textBoxCorrectGuesses.Text = correctGuesses.ToString();
                groupBoxYesOrNo.Visible = true;
            } else {

                labelResultMessage.Visible = true;
                labelResultMessage.ForeColor = Color.Red;
                labelResultMessage.Text = "Sorry, I was thinking of " + computersValue + "    ";
                incorrectGuesses += INCREMENT_EACH_GUESS;
                textBoxIncorrectGuesses.Text = incorrectGuesses.ToString();
                groupBoxYesOrNo.Visible = true;

            }
        }

        /// <summary>
        /// Implement Computer's random Generation
        /// of value between 1 and 10 inclusively
        /// </summary>
        /// <returns>Random value generated by computer</returns>        
        public static int GetComputerValue() {

            int computersValue = RANDOM_CHOICE.Next(MIN_VAL, MAX_VAL);
            return computersValue;
        }

        /// <summary>
        /// Resets some attributes of controls
        /// when Yes radio button is clicked
        /// </summary>
        public void ResetOnYesClick() {

            groupBoxYesOrNo.Visible = false;
            labelResultMessage.Visible = false;
            numericUpDownUserValue.Value = NOT_ACCEPTED_VALUE;
            numericUpDownUserValue.Enabled = true;
            radioButtonYes.Checked = false;
        }

        /// <summary>
        /// Resets some attributes of controls 
        /// when No radio button is clicked
        /// </summary>
        public void ResetOnNoClick() {

            groupBoxYesOrNo.Visible = false;
            labelResultMessage.Visible = false;
            MessageBox.Show("Thanks for playing. Click OK to exit", "GOODBYE!", MessageBoxButtons.OK);
            Application.Exit();
        }


    }
}
